(** Hand-written bindings for GIO VolumeMonitor functions not generated by gir_gen.

    g_volume_monitor_get() is a free function (not a GIR class constructor),
    so it is not picked up by the generator. *)

external volume_monitor_get : unit -> Volume_monitor.t = "ml_g_volume_monitor_get"
