/* Phase 5.3: Generated Text Widget Bindings for GTK4
 *
 * This file contains C FFI bindings for text widget classes.
 * These would normally be generated by gir_gen but are provided here
 * to enable building without running the generator.
 */

#include <gtk/gtk.h>
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/callback.h>

#include "wrappers.h"
#include "ml_gobject.h"

/* ========================================================================= */
/* GtkTextView */
/* ========================================================================= */

CAMLprim value ml_gtk_text_view_new(value unit) {
    CAMLparam1(unit);
    GtkWidget *widget = gtk_text_view_new();
    CAMLreturn(Val_GtkWidget(widget));
}

CAMLprim value ml_gtk_text_view_get_editable(value self) {
    CAMLparam1(self);
    gboolean editable = gtk_text_view_get_editable(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_bool(editable));
}

CAMLprim value ml_gtk_text_view_set_editable(value self, value editable) {
    CAMLparam2(self, editable);
    gtk_text_view_set_editable(GTK_TEXT_VIEW(GtkWidget_val(self)), Bool_val(editable));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_view_get_cursor_visible(value self) {
    CAMLparam1(self);
    gboolean visible = gtk_text_view_get_cursor_visible(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_bool(visible));
}

CAMLprim value ml_gtk_text_view_set_cursor_visible(value self, value visible) {
    CAMLparam2(self, visible);
    gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(GtkWidget_val(self)), Bool_val(visible));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_view_get_wrap_mode(value self) {
    CAMLparam1(self);
    GtkWrapMode mode = gtk_text_view_get_wrap_mode(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_int(mode));
}

CAMLprim value ml_gtk_text_view_set_wrap_mode(value self, value mode) {
    CAMLparam2(self, mode);
    gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(GtkWidget_val(self)), Int_val(mode));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_view_get_left_margin(value self) {
    CAMLparam1(self);
    gint margin = gtk_text_view_get_left_margin(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_int(margin));
}

CAMLprim value ml_gtk_text_view_set_left_margin(value self, value margin) {
    CAMLparam2(self, margin);
    gtk_text_view_set_left_margin(GTK_TEXT_VIEW(GtkWidget_val(self)), Int_val(margin));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_view_get_right_margin(value self) {
    CAMLparam1(self);
    gint margin = gtk_text_view_get_right_margin(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_int(margin));
}

CAMLprim value ml_gtk_text_view_set_right_margin(value self, value margin) {
    CAMLparam2(self, margin);
    gtk_text_view_set_right_margin(GTK_TEXT_VIEW(GtkWidget_val(self)), Int_val(margin));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_view_get_monospace(value self) {
    CAMLparam1(self);
    gboolean monospace = gtk_text_view_get_monospace(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_bool(monospace));
}

CAMLprim value ml_gtk_text_view_set_monospace(value self, value monospace) {
    CAMLparam2(self, monospace);
    gtk_text_view_set_monospace(GTK_TEXT_VIEW(GtkWidget_val(self)), Bool_val(monospace));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_view_get_buffer(value self) {
    CAMLparam1(self);
    GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(GtkWidget_val(self)));
    CAMLreturn(Val_GtkWidget((GtkWidget*)buffer));
}

CAMLprim value ml_gtk_text_view_set_buffer(value self, value buffer) {
    CAMLparam2(self, buffer);
    gtk_text_view_set_buffer(
        GTK_TEXT_VIEW(GtkWidget_val(self)),
        GTK_TEXT_BUFFER(GtkWidget_val(buffer))
    );
    CAMLreturn(Val_unit);
}

/* ========================================================================= */
/* GtkTextBuffer */
/* ========================================================================= */

CAMLprim value ml_gtk_text_buffer_new(value unit) {
    CAMLparam1(unit);
    GtkTextBuffer *buffer = gtk_text_buffer_new(NULL);
    CAMLreturn(Val_GtkWidget((GtkWidget*)buffer));
}

CAMLprim value ml_gtk_text_buffer_get_text(value self) {
    CAMLparam1(self);
    CAMLlocal1(result);
    GtkTextBuffer *buffer = GTK_TEXT_BUFFER(GtkWidget_val(self));
    GtkTextIter start, end;
    gtk_text_buffer_get_start_iter(buffer, &start);
    gtk_text_buffer_get_end_iter(buffer, &end);
    gchar *text = gtk_text_buffer_get_text(buffer, &start, &end, FALSE);
    result = caml_copy_string(text);
    g_free(text);
    CAMLreturn(result);
}

CAMLprim value ml_gtk_text_buffer_set_text(value self, value text) {
    CAMLparam2(self, text);
    gtk_text_buffer_set_text(GTK_TEXT_BUFFER(GtkWidget_val(self)), String_val(text), -1);
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_buffer_get_modified(value self) {
    CAMLparam1(self);
    gboolean modified = gtk_text_buffer_get_modified(GTK_TEXT_BUFFER(GtkWidget_val(self)));
    CAMLreturn(Val_bool(modified));
}

CAMLprim value ml_gtk_text_buffer_set_modified(value self, value modified) {
    CAMLparam2(self, modified);
    gtk_text_buffer_set_modified(GTK_TEXT_BUFFER(GtkWidget_val(self)), Bool_val(modified));
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_buffer_get_line_count(value self) {
    CAMLparam1(self);
    gint count = gtk_text_buffer_get_line_count(GTK_TEXT_BUFFER(GtkWidget_val(self)));
    CAMLreturn(Val_int(count));
}

CAMLprim value ml_gtk_text_buffer_get_char_count(value self) {
    CAMLparam1(self);
    gint count = gtk_text_buffer_get_char_count(GTK_TEXT_BUFFER(GtkWidget_val(self)));
    CAMLreturn(Val_int(count));
}

/* ========================================================================= */
/* GtkTextTag */
/* ========================================================================= */

CAMLprim value ml_gtk_text_tag_new(value unit) {
    CAMLparam1(unit);
    GtkTextTag *tag = gtk_text_tag_new(NULL);
    CAMLreturn(Val_GtkWidget((GtkWidget*)tag));
}

CAMLprim value ml_gtk_text_tag_new_with_name(value name) {
    CAMLparam1(name);
    GtkTextTag *tag = gtk_text_tag_new(String_val(name));
    CAMLreturn(Val_GtkWidget((GtkWidget*)tag));
}

/* ========================================================================= */
/* GtkTextTagTable */
/* ========================================================================= */

CAMLprim value ml_gtk_text_tag_table_new(value unit) {
    CAMLparam1(unit);
    GtkTextTagTable *table = gtk_text_tag_table_new();
    CAMLreturn(Val_GtkWidget((GtkWidget*)table));
}

CAMLprim value ml_gtk_text_tag_table_add(value self, value tag) {
    CAMLparam2(self, tag);
    gboolean result = gtk_text_tag_table_add(
        GTK_TEXT_TAG_TABLE(GtkWidget_val(self)),
        GTK_TEXT_TAG(GtkWidget_val(tag))
    );
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_tag_table_remove(value self, value tag) {
    CAMLparam2(self, tag);
    gtk_text_tag_table_remove(
        GTK_TEXT_TAG_TABLE(GtkWidget_val(self)),
        GTK_TEXT_TAG(GtkWidget_val(tag))
    );
    CAMLreturn(Val_unit);
}

CAMLprim value ml_gtk_text_tag_table_lookup(value self, value name) {
    CAMLparam2(self, name);
    CAMLlocal1(result);
    GtkTextTag *tag = gtk_text_tag_table_lookup(
        GTK_TEXT_TAG_TABLE(GtkWidget_val(self)),
        String_val(name)
    );
    if (tag == NULL) {
        result = Val_int(0); /* None */
    } else {
        result = caml_alloc(1, 0); /* Some */
        Store_field(result, 0, Val_GtkWidget((GtkWidget*)tag));
    }
    CAMLreturn(result);
}

CAMLprim value ml_gtk_text_tag_table_get_size(value self) {
    CAMLparam1(self);
    gint size = gtk_text_tag_table_get_size(GTK_TEXT_TAG_TABLE(GtkWidget_val(self)));
    CAMLreturn(Val_int(size));
}

/* ========================================================================= */
/* GtkTextMark */
/* ========================================================================= */

CAMLprim value ml_gtk_text_mark_get_name(value self) {
    CAMLparam1(self);
    CAMLlocal1(result);
    const gchar *name = gtk_text_mark_get_name(GTK_TEXT_MARK(GtkWidget_val(self)));
    if (name == NULL) {
        result = Val_int(0); /* None */
    } else {
        result = caml_alloc(1, 0); /* Some */
        Store_field(result, 0, caml_copy_string(name));
    }
    CAMLreturn(result);
}

CAMLprim value ml_gtk_text_mark_get_deleted(value self) {
    CAMLparam1(self);
    gboolean deleted = gtk_text_mark_get_deleted(GTK_TEXT_MARK(GtkWidget_val(self)));
    CAMLreturn(Val_bool(deleted));
}

CAMLprim value ml_gtk_text_mark_get_buffer(value self) {
    CAMLparam1(self);
    CAMLlocal1(result);
    GtkTextBuffer *buffer = gtk_text_mark_get_buffer(GTK_TEXT_MARK(GtkWidget_val(self)));
    if (buffer == NULL) {
        result = Val_int(0); /* None */
    } else {
        result = caml_alloc(1, 0); /* Some */
        Store_field(result, 0, Val_GtkWidget((GtkWidget*)buffer));
    }
    CAMLreturn(result);
}
